backend:
  name: github
  repo: XSTATEM/Echips_Wiki
  branch: main
  base_url: https://echips-auth.uzakovv41.workers.dev
  auth_endpoint: auth

media_folder: "public/images" 
public_folder: "/images"     

collections:
  - name: "partner_docs"
    label: "Инструкции для АСЦ"
    folder: "y/partner" # Добавляем 'y/', чтобы путь был точным
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Тело статьи", name: "body", widget: "markdown"}