backend:
  name: github
  repo: XSTATEM/Echips_Wiki 
  branch: main

media_folder: "public" 
public_folder: "/"     

collections:
  - name: "partner_docs"
    label: "Инструкции для АСЦ"
    folder: "partner" 
    create: true      
    fields:
      - {label: "Тело статьи", name: "body", widget: "markdown"}