backend:
  name: github
  repo: XSTATEM/Echips_Wiki
  branch: main
  base_url: https://sveltia-cms-auth.pages.dev 

media_folder: "public/images" 
public_folder: "/images"     

collections:
  - name: "partner_docs"
    label: "Инструкции для АСЦ"
    folder: "partner" 
    create: true      
    fields:
      - {label: "Тело статьи", name: "body", widget: "markdown"}